apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Release.Namespace }}
spec:
  template:
    spec:
      containers:
      - name: {{ .Values.name }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: Always
        env:
        {{- range $key, $val := .Values.env }}
        - name: {{ $key }}
          value: {{ $val }}
        {{- end }}
        volumeMounts:
        - mountPath: {{ .Values.volume.mountPath }}
          name: {{ .Values.volume.name }}
      restartPolicy: Never
      volumes:
      - name: {{ .Values.volume.name }}
        persistentVolumeClaim:
          claimName: {{ .Values.volume.claimName }}
          readOnly: {{ .Values.volume.readOnly }}